services:
    app:
#        image: golang:1.22-bookworm
        build:
            context: ./
            dockerfile: docker/go/Dockerfile
        ports:
            - "8080:80"
        restart: always
        depends_on:
            db:
                condition: service_healthy
        env_file:
            - .env.example
        networks:
            - default
#        platform: linux/amd64
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=product
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
          - "5433:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - default
#        platform: linux/amd64
networks:
    default:
        name: product-network
volumes:
    postgres_data: